version: "3"
services:
  keycloak:
    build:
      context: keycloak
      dockerfile: Dockerfile
    ports:
      - 8180:8080
    network_mode: bridge
  postgres:
    image: postgres:9.6.16-alpine
    environment:
      POSTGRES_DB: goms
      POSTGRES_USER: goms
      POSTGRES_PASSWORD: goms
    ports:
      - 5432:5432
    network_mode: bridge
  prometheus:
    build:
      context: monitoring/prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    network_mode: bridge
  grafana:
    build:
      context: monitoring/grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    network_mode: bridge
  rabbitmq:
    # ui at: http://localhost:15672
    # un: guest, pw: guest
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    network_mode: bridge
  neo4j:
    # ui at: http://localhost:7474
    # un: neo4j, pw: neo4j
    image: neo4j:latest
    volumes:
      - "$HOME/neo4j/data:/data"
      - "$HOME/neo4j/conf/:/conf/"
    ports:
      - 7474:7474
      - 7687:7687
    network_mode: bridge
