version: "3"
services:
  keycloak:
    build:
      context: keycloak
      dockerfile: Dockerfile
    ports:
      - 8180:8080
    network_mode: bridge
  postgres:
    image: postgres:9.6.16-alpine
    environment:
      POSTGRES_DB: goms
      POSTGRES_USER: goms
      POSTGRES_PASSWORD: goms
    ports:
      - 5432:5432
    network_mode: bridge
  prometheus:
    build:
      context: monitoring/prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    network_mode: bridge
  grafana:
    build:
      context: monitoring/grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    network_mode: bridge
